AlphaWeb/Models/ErrorViewModel.cs
using System;

namespace AlphaWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AlphaWeb/Controllers/PrivateController.cs
using BusinessLogicLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Model.WebModel;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace WebAlpha.Controllers
{
    public class PrivateController : Controller
    {
        BusinessController bc = new BusinessController();
        Guid userID = Guid.Empty;
        bool access = false;

        public void CheckLogin()
        {
            //Check login ToDo use access token to get access
            if (HttpContext.Session != null)
            {
                string value = HttpContext.Session.GetString("UserID");

                if (value != null && value != string.Empty)
                {
                    userID = Guid.Parse(value);
                    access = true;
                }
            }            
        }

      
        public ActionResult Login()
        {
            return View();
        }
        

        [HttpPost]
        public ActionResult Login(User input)
        {
            User user = bc.GetUserByLogin(input.UserName, input.Password);
            
            if (user != null)
            {
                HttpContext.Session.SetString("UserID", user.UserID.ToString());
                return RedirectToAction("Index", "private");
            }

            return View();
        }
        public ActionResult Logout()
        {
            HttpContext.Session.SetString("UserID", string.Empty);
            return RedirectToAction("Login", "private");
        }

        // GET: PrivateController
        public ActionResult Index()
        {
            CheckLogin();           
            if (access == false)
            {
                return RedirectToAction("Login", "private");
            }

            User user = bc.GetUserByID(userID);
            return View(user);
        }


        public ActionResult CreateReview(Guid id)
        {
            CheckLogin();
            if (access == false)
            {
                return RedirectToAction("Login", "private");
            }

            Company company = bc.GetCompanyById(id);
            
            if (company != null)
            {
                Review model = new Review()
                {
                    CompanyID = id
                };
                return View(model);
            }
            return RedirectToAction("Index", "public");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateReview(Review input)
        {
            CheckLogin();
            if (access == false)
            {
                return RedirectToAction("Login", "private");
            }

            input.UserID = userID;
            input.Timestamp = DateTime.Now;
            input.ReviewID = Guid.NewGuid();
            bc.ReviewCreate(input);

            return RedirectToAction("ShowCompany", "public", new { id = input.CompanyID });
        }

         public ActionResult UserEdit()
         {
            CheckLogin();
            if (access == false)
            {
                return RedirectToAction("Login", "private");
            }

            User model = bc.GetUserByID(userID);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UserEdit(User input)
        {
            CheckLogin();
            if (access == false)
            {
                return RedirectToAction("Login", "private");
            }

            bc.UserUpdate(input);

            return RedirectToAction("Index", "private");
        }
        
    }
}

AlphaWeb/Controllers/PublicController.cs
using BusinessLogicLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Model.WebModel;
using System;
using System.Collections.Generic;

namespace WebAlpha.Controllers
{
    public class PublicController : Controller
    {
        BusinessController bc = new BusinessController();
        // GET: PublicController
        public ActionResult Index()
        {
            List<Company> model = bc.GetCompanyList();
            return View(model);
        }

        public ActionResult ShowCompany(Guid id)
        {
            Company model = bc.GetCompanyById(id);
            return View(model);
        }

        public ActionResult ViewProfile(Guid id)
        {
            UserPublic model = bc.GetPublicUserByID(id);
            return View(model);
        }

        public ActionResult UserList()
        {
            List<UserPublic> model = bc.GetAllUsers();
            return View(model);
        }

        public ActionResult Image(Review input)
        {
            string respont = input.Base64String;

            if (input.Base64String == null)
            {
                respont = bc.GetImage("Images\\Burger1.jpg");
            }

            return this.File(respont, "image/jpg", "image.jpg");
        }

        public ActionResult CreateCompany()
        {
            Company model = new Company();
            return View(model);
        }


        [HttpPost]
        public ActionResult CreateCompany(Company input)
        {
            bc.CompanyCreate(input);
            return RedirectToAction("Index", "public");
        }

        public ActionResult CreateUser()
        {
            User model = new User();
            return View(model);
        }


        [HttpPost]
        public ActionResult CreateUser(User input)
        {
            bc.CreateUser(input);
            return RedirectToAction("UserList", "public");
        }
    }
}

AlphaWeb/Views/Private/CreateReview.cshtml
@model Model.WebModel.Review

@{
    ViewData["Title"] = "CreateReview";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CreateReview</h1>

<h4>Review</h4>
<hr />
<div class="row">
    <div class="col-md-4">
       <form asp-action="CreateReview"  asp-controller="Private" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="CompanyID" type="hidden"/>
            
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TasteRating" class="control-label"></label>
                <input asp-for="TasteRating" class="form-control" />
                <span asp-validation-for="TasteRating" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TextureRating" class="control-label"></label>
                <input asp-for="TextureRating" class="form-control" />
                <span asp-validation-for="TextureRating" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="VisualRating" class="control-label"></label>
                <input asp-for="VisualRating" class="form-control" />
                <span asp-validation-for="VisualRating" class="text-danger"></span>
            </div>            
           
            <div class="form-group">
               <div class="custom-file">
                     <input asp-for="Image" type="file" class="custom-file-input fileUpload" />
                     <label class="custom-file-label fileLabel">Choose file</label>
               </div>
            </div>            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlphaWeb/Views/Private/Index.cshtml
@model Model.WebModel.User
@{
    ViewData["Title"] = "UserProfile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Model.UserName</h1>

<div class="row">
    @await Html.PartialAsync("Partial/ProfileView", Model)
</div>

<div class="row">
    @await Html.PartialAsync("Partial/ReviewList", Model.ReviewList)
</div>

AlphaWeb/Views/Private/Login.cshtml
@model Model.WebModel.User

@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Login</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>           
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>           
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlphaWeb/Views/Private/Partial/ProfileView.cshtml
@model Model.WebModel.User

<div>
    <h4>User</h4>
    <hr />
    <dl class="row">      
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>   
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfileText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfileText)
        </dd>
    </dl>
</div>
@*<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>*@

AlphaWeb/Views/Private/UserEdit.cshtml
@model Model.WebModel.User

@{
    ViewData["Title"] = "UserEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>UserEdit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UserEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>           
            <div class="form-group">
                <label asp-for="ProfileText" class="control-label"></label>
                <input asp-for="ProfileText" class="form-control" />
                <span asp-validation-for="ProfileText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlphaWeb/Views/Private/UserProfile.cshtml
@model Model.WebModel.User
@{
    ViewData["Title"] = "UserProfile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Model.UserName</h1>

<div class="row">
    @await Html.PartialAsync("Partial/ProfileView", Model)
</div>

<div class="row">
    @await Html.PartialAsync("Partial/ReviewList", Model.ReviewList)
</div>

@Html.ActionLink("View", "UserEdit", null, new { @class = "btn btn-primary"})

AlphaWeb/Views/Public/CreateCompany.cshtml
@model Model.WebModel.Company

@{
    ViewData["Title"] = "CreateCompany";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create Company</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCompany">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpeningHours" class="control-label"></label>
                <input asp-for="OpeningHours" class="form-control" />
                <span asp-validation-for="OpeningHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlphaWeb/Views/Public/CreateUser.cshtml
@model Model.WebModel.User

@{
    ViewData["Title"] = "CreateUSer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CreateUSer</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateUSer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>            
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>           
            <div class="form-group">
                <label asp-for="ProfileText" class="control-label"></label>
                <input asp-for="ProfileText" class="form-control" />
                <span asp-validation-for="ProfileText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AlphaWeb/Views/Public/Index.cshtml
@model IEnumerable<Model.WebModel.Company>

<div class="row">
    @await Html.PartialAsync("Partial/CompanyList", Model)
</div>

AlphaWeb/Views/Public/ShowCompany.cshtml
@model Model.WebModel.Company

@{
    ViewData["Title"] = "ShowCompany";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Model.Name</h1>
<div class="row">
@Html.ActionLink("Back", "Index", "public", null, new { @class = "btn btn-primary"})
</div>

<div class="row">
    @await Html.PartialAsync("Partial/CompanyView", Model)
</div>

<div class="row">
    @await Html.PartialAsync("Partial/GoogleMapView", Model)
</div>

<div class="row" style="padding-top:15px">     
    @Html.ActionLink("Opret Review", "CreateReview", "private", new { id=Model.CompanyID }, new { @class = "btn btn-primary"})
</div>

<div class="row">
    @await Html.PartialAsync("Partial/ReviewList", Model.ReviewList)
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

AlphaWeb/Views/Public/UserList.cshtml
@model IEnumerable<Model.WebModel.UserPublic>

@{
    ViewData["Title"] = "UserList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>UserList</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>           
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProfileText)
            </th>  
            <th>
                Review counter
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>            
            <td>
                @Html.DisplayFor(modelItem => item.ProfileText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReviewList.Count)
            </td>
            <td>
                @Html.ActionLink("View profile", "ViewProfile", new { id=item.UserID  }, new { @class = "btn btn-primary"})
            </td>
        </tr>
}
    </tbody>
</table>

AlphaWeb/Views/Public/ViewProfile.cshtml
@model Model.WebModel.User

@{
    ViewData["Title"] = "ViewProfile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>View Profile: @Model.UserName</h1>

<div>
    <hr />
    <dl class="row">        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfileText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfileText)
        </dd>
    </dl>
</div>
<div class="row">
    @await Html.PartialAsync("Partial/ReviewList", Model.ReviewList)
</div>

AlphaWeb/Views/Shared/Partial/CompanyList.cshtml
@model IEnumerable<Model.WebModel.Company>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZipCode)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZipCode)
            </td>
            <td>
                @Html.ActionLink("View", "ShowCompany", new {  id=item.CompanyID  }, new { @class = "btn btn-primary"})
            </td>
        </tr>}
    </tbody>
</table>

AlphaWeb/Views/Shared/Partial/CompanyView.cshtml
@model Model.WebModel.Company

<div>
    <dl class="row">      
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OpeningHours)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OpeningHours)
        </dd>        
    </dl>
</div>

AlphaWeb/Views/Shared/Partial/GoogleMapView.cshtml
@model Model.WebModel.Company

<div class="mapouter">
    <div class="gmap_canvas">
        <iframe width="300" height="300" id="gmap_canvas" src="@Model.GetGoogleMapLink()" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
        <br>
        <style>.mapouter{position:relative;text-align:right;height:300px;width:300px;}</style>
        <style>.gmap_canvas {overflow:hidden;background:none!important;height:300px;width:300px;}</style>
    </div>
</div>

AlphaWeb/Views/Shared/Partial/ReviewList.cshtml
@model IEnumerable<Model.WebModel.Review>

<h1>ReviewList</h1>
<table class="table">
    <thead>
        <tr>
             <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TasteRating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TextureRating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VisualRating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Timestamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>          
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
             <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TasteRating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TextureRating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VisualRating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Timestamp)
            </td>
            <td>
                <img src="~/images/Burger1.jpg" class="detailImage" height="75" />
               @* <img src="data:image;base64,@Url.Action("Image","public", item))" width="80" height="80"/>  *@  
               @*<img src="@Url.Action("Image","public", item)"/>*@

                @Html.DisplayFor(modelItem => item.Image)
            </td>            
        </tr>
}
    </tbody>
</table>

AlphaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AlphaWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AlphaWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Private" asp-action="Index">User Profile</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Public" asp-action="Index">CompanyList</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Public" asp-action="UserList">UserList</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Private" asp-action="Login">Login</a>
                        </li> <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Private" asp-action="Logout">Logout</a>
                        </li> </li> <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Public" asp-action="CreateUser">Create User</a>
                        </li> </li> <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Public" asp-action="CreateCompany">Create Company</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AlphaWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>